version: '3'

services:
  mysql_db:
    image: 'mysql:8'
    container_name: mysql8
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=spring_boot_db
      - MYSQL_USER=springboot
      - MYSQL_PASSWORD=password
    ports:
      - 3306:3306

  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin'
    container_name: phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=spring_boot_db
      - MYSQL_USERNAME=springboot
      - MYSQL_PASSWORD=password
      - PMA_HOST=mysql_db
    ports:
      - 8000:80
    depends_on:
      - mysql_db

  springboot:
    build: .
    container_name: springboot-app
    depends_on:
      - mysql_db
    ports:
      - 8888:8888
    environment:
      - DATABASE_HOST=mysql_db
      - DATABASE_USER=springboot
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=spring_boot_db
      - DATABASE_PORT=3306
